fix: do not try to access a propery of `errors` if it is null
This will fix an error like:

  Debug: internal, implementation, error
      TypeError: Cannot read property 'dd02ecb82ff38dd14d741dacad7e28b737b3997193617b205b062bf683c626bd' of null
      at handler (/home/ark/ark-core/packages/core-p2p/lib/server/versions/1/handlers.js:338:26)
      at <anonymous>